version: '3.9'
services:
  brewnotes:
    build: .
    ports:
      - "8087:8080"
    environment:
      - APP_PORT=8080
      - DATA_DIR=/data
      - DB_PATH=/data/app.db
      - UPLOAD_DIR=/data/uploads
      - PUID=99
      - PGID=100
    volumes:
      - ./data:/data
